./src/design/common/Multiplexer.v
./src/design/common/RISCV_PROCESSOR.v
./src/design/m_standard/Division.v
./src/design/m_standard/Multiplication.v
./src/design/m_standard/RV32M.v
./src/design/newcache/Dcache.v
./src/design/newcache/cache.v
./src/design/newcache/memory.v
./src/design/newcache/myip_v1_0.v
./src/design/newcache/myip_v1_0_M00_AXI.v
./src/design/newcache/myip_v1_0_S00_AXI.v
./src/design/newcache/state_mem.v
./src/design/pipeline/BHT.v
./src/design/pipeline/CONTROL_UNIT.v
./src/design/pipeline/CSR_FILE.v
./src/design/pipeline/DECODE_UNIT.v
./src/design/pipeline/EXSTAGE.v
./src/design/pipeline/IMM_EXT.v
./src/design/pipeline/INS_TYPE_ROM.v
./src/design/pipeline/PIPELINE.v
./src/design/pipeline/Peripheral.v
./src/design/pipeline/REG_ARRAY.v
./src/design/pipeline/STATE_REG.v
./src/simulation/TEST_RISCV_PROCESSOR.v
